FROM python:3.9-buster

RUN mkdir app
WORKDIR /app

ENV PATH="${PATH}:/root/.local/bin"
ENV PYTHONPATH=.

COPY requirements-backend.txt .
RUN pip install --upgrade pip
RUN pip install -r requirements-backend.txt

COPY backend/src/ .
