FROM node:lts
RUN mkdir /home/node/app && chown node:node /home/node/app
RUN mkdir /home/node/app/node_modules && chown node:node /home/node/app/node_modules
WORKDIR  /home/node/app

RUN npm install -g @angular/cli

USER node
COPY ./frontend/package.json ./frontend/package-lock.json ./
#RUN npm ci --quiet
COPY --chown=node:node ./frontend .
